"""
ARMG Phase 2: Baseline Stateless Text-to-SQL Pipeline Runner.

Executes a strictly linear, single-pass Text-to-SQL pipeline:
User Query -> Introspect -> Prune -> Prompt -> Qwen -> Extract -> SQLGlot Guard -> PostgreSQL Execute -> Result

Enforces Phase 2 boundaries:
- Exactly 1 generation attempt.
- 0 retries.
- 0 error feedback loops.
- 0 memory / persistent state.
"""

import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, List, Optional

# Ensure workspace root is in sys.path when executed directly
repo_root = str(Path(__file__).resolve().parent.parent)
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

from agents.schema_introspector import SchemaIntrospector, format_catalog_to_markdown
from agents.schema_pruner import SchemaPruner
from agents.sql_generator import SQLGenerator, GenerationResult
from environment.postgres import PostgreSQLEnvironment
from validation.execution_validator import ExecutionValidator


@dataclass
class BaselineExecutionResult:
    """Encapsulates telemetry and outcome of a stateless single-pass query execution."""
    question: str
    pruned_tables: List[str]
    schema_markdown: str
    raw_response: str
    extracted_sql: str
    validation_passed: bool
    validation_error: Optional[str]
    execution_status: str  # "SUCCESS", "VALIDATION_FAILED", "EXECUTION_FAILED", "GENERATION_FAILED"
    execution_error: Optional[str]
    rows: List[Any] = field(default_factory=list)
    row_count: int = 0
    generation_latency_ms: float = 0.0
    execution_latency_ms: float = 0.0
    total_latency_ms: float = 0.0
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None

    @property
    def is_success(self) -> bool:
        return self.execution_status == "SUCCESS"


class BaselinePipeline:
    """Linear, stateless Text-to-SQL baseline orchestrator."""

    def __init__(
        self,
        env: Optional[PostgreSQLEnvironment] = None,
        generator: Optional[SQLGenerator] = None,
    ):
        self.env = env or PostgreSQLEnvironment()
        self.introspector = SchemaIntrospector(env=self.env)
        self.pruner = SchemaPruner()
        self.validator = ExecutionValidator()
        self.generator = generator or SQLGenerator()

    def run(self, question: str) -> BaselineExecutionResult:
        """Execute a single-pass Text-to-SQL query without retries or feedback.
        
        Args:
            question: Natural language user question.
            
        Returns:
            BaselineExecutionResult capturing all outputs, status codes, and metrics.
        """
        pipeline_start = time.perf_counter()

        # Step 1: Introspect catalog
        catalog = self.introspector.get_raw_catalog()

        # Step 2: Deterministically prune schema tables
        pruned_tables = self.pruner.prune(question)

        # Step 3: Format pruned schema Markdown
        schema_markdown = format_catalog_to_markdown(catalog, filter_tables=pruned_tables)

        # Step 4: Generate SQL via local Qwen (single attempt)
        gen_result: GenerationResult = self.generator.generate(question, schema_markdown)

        if not gen_result.extracted_sql:
            total_elapsed = (time.perf_counter() - pipeline_start) * 1000.0
            return BaselineExecutionResult(
                question=question,
                pruned_tables=pruned_tables,
                schema_markdown=schema_markdown,
                raw_response=gen_result.raw_response,
                extracted_sql="",
                validation_passed=False,
                validation_error="Empty SQL generated by LLM.",
                execution_status="GENERATION_FAILED",
                execution_error="No SQL could be extracted from model output.",
                generation_latency_ms=gen_result.generation_duration_ms,
                total_latency_ms=round(total_elapsed, 3),
                prompt_tokens=gen_result.prompt_tokens,
                completion_tokens=gen_result.completion_tokens,
            )

        # Step 5: SQLGlot SELECT-Only Safety Guard
        is_valid, val_error = self.validator.validate(gen_result.extracted_sql)
        if not is_valid:
            total_elapsed = (time.perf_counter() - pipeline_start) * 1000.0
            return BaselineExecutionResult(
                question=question,
                pruned_tables=pruned_tables,
                schema_markdown=schema_markdown,
                raw_response=gen_result.raw_response,
                extracted_sql=gen_result.extracted_sql,
                validation_passed=False,
                validation_error=val_error,
                execution_status="VALIDATION_FAILED",
                execution_error=f"SQLGlot validation rejected: {val_error}",
                generation_latency_ms=gen_result.generation_duration_ms,
                total_latency_ms=round(total_elapsed, 3),
                prompt_tokens=gen_result.prompt_tokens,
                completion_tokens=gen_result.completion_tokens,
            )

        # Step 6: PostgreSQL Physical Execution (single attempt, zero repair)
        exec_result = self.env.execute(gen_result.extracted_sql)
        total_elapsed = (time.perf_counter() - pipeline_start) * 1000.0

        if exec_result.is_success:
            status = "SUCCESS"
            exec_err = None
        else:
            status = "EXECUTION_FAILED"
            exec_err = exec_result.error

        return BaselineExecutionResult(
            question=question,
            pruned_tables=pruned_tables,
            schema_markdown=schema_markdown,
            raw_response=gen_result.raw_response,
            extracted_sql=gen_result.extracted_sql,
            validation_passed=True,
            validation_error=None,
            execution_status=status,
            execution_error=exec_err,
            rows=exec_result.rows,
            row_count=exec_result.row_count,
            generation_latency_ms=gen_result.generation_duration_ms,
            execution_latency_ms=exec_result.execution_time_ms,
            total_latency_ms=round(total_elapsed, 3),
            prompt_tokens=gen_result.prompt_tokens,
            completion_tokens=gen_result.completion_tokens,
        )


def main():
    """CLI demonstration of baseline pipeline on representative queries."""
    sample_queries = [
        "What is the total gross revenue?",
        "What is the total revenue by region?",
        "What is the net profit by product category and calendar year?",
    ]

    pipeline = BaselinePipeline()
    print("=" * 80)
    print("ARMG PHASE 2: STATELESS BASELINE TEXT-TO-SQL EXECUTION")
    print("=" * 80)

    for i, q in enumerate(sample_queries, 1):
        print(f"\n[Query {i}] Question: {q}")
        res = pipeline.run(q)
        print(f"  - Pruned Tables: {res.pruned_tables}")
        print(f"  - Extracted SQL:\n      {res.extracted_sql.replace(chr(10), chr(10) + '      ')}")
        print(f"  - Validation: {'PASSED' if res.validation_passed else 'FAILED (' + str(res.validation_error) + ')'}")
        print(f"  - Execution Status: {res.execution_status}")
        if res.execution_error:
            print(f"  - Error: {res.execution_error}")
        print(f"  - Rows Returned: {res.row_count}")
        print(f"  - Latency: Gen {res.generation_latency_ms}ms | Exec {res.execution_latency_ms}ms | Total {res.total_latency_ms}ms")
        print(f"  - Tokens: Prompt {res.prompt_tokens} | Completion {res.completion_tokens}")


if __name__ == "__main__":
    main()
